### ISSUE TITLE
Is it possible to ignore some errors?

### ISSUE THREAD

**Issue by maliayas** [SublimeLinter/SublimeLinter-mdl#1]
Is it possible to ignore some errors?

**Comment by roadhump** [comment]
Yes, but I don't remember correctly how, dig https://github.com/mivok/markdownlint

**Comment by KyleKing** [comment]
I also ran into a similar issue, using the array syntax for args didn't work (i.e. `"args": ["-r ~MD013"]`), but specifying the args as a single string does: `"args": "-r ~MD013"`

For more info on `mdl`, see [the updated guide on arguments](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md#specifying-which-rules-mdl-processes) and the [full list of RULES](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md)
