### ISSUE TITLE
Wanna transfer this to the SublimeLinter group?

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter-mdl#3]
We'd like to improve the compatibility of this plugin and usually it's easier if members of the SL group can just go and make a fix rather than having to go through a pull request. 

So @roadhump, if you want to transfer this to me (@braver) I'll put it in the group and make sure you still have access.

**Comment by roadhump** [comment]
@braver Thank you, it would be a pleasure for me, I do not use ST now.

**Comment by roadhump** [comment]
@braver Also, will it be possible for you to take https://github.com/roadhump/SublimeLinter-contrib-eslint_d to SL group as well?
