### ISSUE TITLE
incorrect implementation of linter settings

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter-mdl#4]
@kaste I'm reviewing some of the plugins. I noticed that this linter tells users there is a `bundle_exec` setting, but it then doesn't read the setting in a way that users can set this via linter settings. In stead, apparently you're supposed to set it in a global setting. My guess here is that no-one uses the setting. But perhaps it's also possible set the executable in a way that would work?

https://github.com/SublimeLinter/SublimeLinter-mdl/blob/385b015146b84e8716b3c44383ca5874b39f6eef/linter.py#L16

---

edit, or I'm just reading it incorrectly. never mind.

**Comment by kaste** [comment]
I think this works. This is of course a Ruby linter, and I wonder if we/Sublime has any Ruby users anymore bc we never improve anything here.

**Comment by braver** [comment]
LOL, probably. Ruby does have a hard time pretty much everywhere. I'm always surprised it's actually used for a lot of stuff, because at the tooling/editor end, all I hear is that nothing works (and don't even try on Windows). But this particular thing should work indeed. Anyway 🤷‍♂️
